---
- project:
    name: core-config-seed-go
    project-name: core-config-seed-go
    project: core-config-seed-go
    mvn-settings: core-config-seed-go-settings
    pre_build_script: 'make prepare && make test'
    x86_build_script: 'make build && make docker_core_config_seed_go'
    arm64_build_script: 'make build && make docker_core_config_seed_go_arm'
    stream:
      - 'california':
          branch: 'california'
    jobs:
      - '{project-name}-{stream}-verify-go':
          build_script: '{x86_build_script}'
          status-context: '{project-name}-{stream}-verify'
      - '{project-name}-{stream}-verify-go-arm64':
          build_script: '{arm64_build_script}'
          status-context: '{project-name}-{stream}-verify-arm64'
      - '{project-name}-{stream}-merge-go':
          build_script: '{x86_build_script}'
          post_build_script: !include-raw-escape: shell/core-config-seed-go-docker-push.sh
      - '{project-name}-{stream}-merge-go-arm64':
          build_script: '{arm64_build_script}'
          post_build_script: !include-raw-escape: shell/core-config-seed-go-docker-push.sh
      - '{project-name}-{stream}-stage-go':
          build_script: '{x86_build_script}'
          post_build_script: !include-raw-escape: shell/core-config-seed-go-docker-push.sh
      - '{project-name}-{stream}-stage-go-arm64':
          build_script: '{arm64_build_script}'
          post_build_script: !include-raw-escape: shell/core-config-seed-go-docker-push.sh
